const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"律师管理",
			            "menuJump":"列表",
			            "tableName":"lvshi"
			        }
			    ],
			    "menu":"律师管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"客户管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"客户管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"案源信息管理",
                        "menuJump":"列表",
                        "tableName":"anyuan"
                    }
                ],
                "menu":"案源信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "审核",
                            "删除"
                        ],
                        "menu":"案件信息管理",
                        "menuJump":"列表",
                        "tableName":"anyuanYuyue"
                    }
                ],
                "menu":"案件信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"结案评论管理",
                        "menuJump":"列表",
                        "tableName":"jieanpingluen"
                    }
                ],
                "menu":"结案评论管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"事务所意见管理",
                        "menuJump":"列表",
                        "tableName":"kehuyijian"
                    }
                ],
                "menu":"事务所意见管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "删除"
			            ],
			            "menu":"律师意见管理",
			            "menuJump":"列表",
			            "tableName":"lvshiCommentback"
			        }
			    ],
			    "menu":"律师意见管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"案源类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryAnyuan"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"公告类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryNews"
			        }
			    ],
			    "menu":"基础数据管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告信息管理",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"公告信息管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
	{
	    "backMenu":[
	        {
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "审核"
	                    ],
	                    "menu":"案源信息管理",
	                    "menuJump":"列表",
	                    "tableName":"anyuan"
	                }
	            ],
	            "menu":"案源信息管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
							"修改"
	                    ],
	                    "menu":"案件信息管理",
	                    "menuJump":"列表",
	                    "tableName":"anyuanYuyue"
	                }
	            ],
	            "menu":"案件信息管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"结案评论管理",
	                    "menuJump":"列表",
	                    "tableName":"jieanpingluen"
	                }
	            ],
	            "menu":"结案评论管理"
	        }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"律师意见管理",
			            "menuJump":"列表",
			            "tableName":"lvshiCommentback"
			        }
			    ],
			    "menu":"律师意见管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"公告信息管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"公告信息管理"
	        }
	    ],
	    "frontMenu":[],
	    "hasBackLogin":"是",
	    "hasBackRegister":"否",
	    "hasFrontLogin":"否",
	    "hasFrontRegister":"否",
	    "roleName":"律师",
	    "tableName":"lvshi"
	},
	{
	    "backMenu":[
	        {
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"律师管理",
			            "menuJump":"列表",
			            "tableName":"lvshi"
			        }
			    ],
			    "menu":"律师管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
			                "新增",
			                "修改",
	                        "删除"
	                    ],
	                    "menu":"案源信息管理",
	                    "menuJump":"列表",
	                    "tableName":"anyuan"
	                }
	            ],
	            "menu":"案源信息管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
							"评论"
	                    ],
	                    "menu":"案件信息管理",
	                    "menuJump":"列表",
	                    "tableName":"anyuanYuyue"
	                }
	            ],
	            "menu":"案件信息管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
			                "删除"
	                    ],
	                    "menu":"结案评论管理",
	                    "menuJump":"列表",
	                    "tableName":"jieanpingluen"
	                }
	            ],
	            "menu":"结案评论管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
			                "新增",
			                "删除"
	                    ],
	                    "menu":"事务所意见管理",
	                    "menuJump":"列表",
	                    "tableName":"kehuyijian"
	                }
	            ],
	            "menu":"事务所意见管理"
	        }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除"
			            ],
			            "menu":"律师意见管理",
			            "menuJump":"列表",
			            "tableName":"lvshiCommentback"
			        }
			    ],
			    "menu":"律师意见管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"公告信息管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"公告信息管理"
	        }
	    ],
	    "frontMenu":[],
	    "hasBackLogin":"是",
	    "hasBackRegister":"否",
	    "hasFrontLogin":"否",
	    "hasFrontRegister":"否",
	    "roleName":"客户",
	    "tableName":"yonghu"
	}
]
    }
}
export default menu;
